repository:
  name: beetrix
  description: |
    High-performance and reliable InfluxDB writer for Elixir.
  private: true
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  topics: library

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ["Bless"]
      enforce_admins: false
      restrictions: null
